name: e2e Test Automation
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

# workflow permissions
permissions:
    checks: write
    contents: write
    issues: write
    pull-requests: write

env:
  CI: true

jobs:
  test:
    name: e2e Test Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Test Repo
        uses: actions/checkout@v4

      - name: log
        run: ls
          
      - name: Navigate to Playwright directory
        run: cd playwright/

      - name: log
        run: ls

      - name: Use NodeJS 20
        if: success()
        uses: actions/setup-node@v4
        with: 
          node-version: 20
          cache: npm

      - name: Install Playwright Dependencies
        if: success()
        run: |
          ls
          npm ci || npm i
