name: e2e Test Automation
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

# workflow permissions
permissions:
    checks: write
    contents: write
    issues: write
    pull-requests: write

env:
  CI: true

jobs:
  test:
    name: e2e Test Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Test Repo
        uses: actions/checkout@v4

      - name: Install Playwright Dependencies
        if: success()
        working-directory: playwright
        run: npm install

